services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"   # HTTP
      - "6334:6334"   # gRPC (optional)
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped
